FROM localhost/appcafe/open-liberty:beta-instanton

# These defaults are overridden by `--build-arg` arguments in pom.xml
ARG NAME=placeholder
ARG VERSION=0.0.0
ARG REVISION=placeholder
ARG AUTHORS=placeholder@example.com
ARG VENDOR=Placeholder
ARG SUMMARY=Placeholder
ARG DESCRIPTION=Placeholder
ARG URL=https://example.com/
ARG SOURCE=https://example.com/
# https://spdx.org/licenses/
ARG LICENSE="Apache-2.0"
ARG VERBOSE=false
ARG OPENJ9_SCC=true
ARG OPENJ9_JAVA_OPTIONS=""
ARG CONSOLE_FORMAT="simple"

# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
LABEL \
  org.opencontainers.image.authors="${AUTHORS}" \
  org.opencontainers.image.vendor="${VENDOR}" \
  org.opencontainers.image.url="${URL}" \
  org.opencontainers.image.source="${SOURCE}" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}" \
  vendor="${VENDOR}" \
  name="${NAME}" \
  org.opencontainers.image.title="${NAME}" \
  version="${VERSION}-${REVISION}" \
  summary="${SUMMARY}" \
  description="${DESCRIPTION}" \
  org.opencontainers.image.description="${DESCRIPTION}" \
  maintainer="${AUTHORS}" \
  org.opencontainers.image.authors="${AUTHORS}" \
  org.opencontainers.image.licenses="${LICENSE}" \
  license="${LICENSE}"

COPY --chown=default:root target/liberty/wlp/usr/servers/reactive-service-b/server.xml /config/server.xml
COPY --chown=default:root target/liberty/wlp/usr/servers/reactive-service-b/jvm.options /config/jvm.options
COPY --chown=default:root target/liberty/wlp/usr/servers/reactive-service-b/bootstrap.properties /config/bootstrap.properties
COPY --chown=default:root target/reactive-service-b.war /config/apps

USER root
COPY lib/OpenJ9-JDK17-x86-64_linux-20230517-224319.tar.gz /opt/
RUN dnf install -y iptables && \
    rm -rf /opt/java/java-ea && \
    tar xzvf /opt/OpenJ9-JDK17-x86-64_linux-20230517-224319.tar.gz -C /opt/java/ && \
    mv /opt/java/jdk /opt/java/java-ea
USER 1001

ENV WLP_LOGGING_CONSOLE_FORMAT=${CONSOLE_FORMAT}

# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
